packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - sharp
  - workerd
