import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import * as authSchema from "./auth.schema"; // tables generated by Better‑Auth

export const page = sqliteTable("page", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
});

// Export types for TypeScript
export type Page = typeof page.$inferSelect;
export type NewPage = typeof page.$inferInsert;
